language: go

go:
  - master
  - 1.13.x

branches:
  only:
  - master

script:
  - go get -t -v ./...
  - go vet ./...
  - bash ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
  